### ISSUE TITLE
Support querying nodes 

### ISSUE THREAD

**Issue by davidtwco** [mockersf/jenkins-api.rs#14]
Jenkins has an API available at `/computer/api/json` that allows information about nodes to be returned - it would be useful for this library to expose an API for this also.

**Comment by davidtwco** [comment]
I've just noticed that it seems like this is currently in-progress.

**Comment by mockersf** [comment]
Hello !

I added it a few days ago but was trying it out in another project to check it was usable before releasing. 

It's done now !
