### ISSUE TITLE
library now logs info messages under normal use

### ISSUE THREAD

**Issue by clux** [mockersf/jenkins-api.rs#17]
Hi again :man_facepalming: 

normal practice for libraries seems to be to log as `debug!` or `trace!`

upgraded jenkins_api and this thing hits me constantly now:
https://github.com/mockersf/jenkins-api.rs/blob/0667d43277e182e5303a2eec4e1cd84f8eaf36f2/src/client/mod.rs#L48

any chance we could downgrade it to a lower level message?

**Comment by mockersf** [comment]
Hello !

I'm usually using [env_logger](https://docs.rs/env_logger/0.5.10/env_logger/#enabling-logging) or [fern](https://docs.rs/fern/0.5.5/fern/struct.Dispatch.html#method.level_for) that let me set my log level per module, so it was not an issue for me, but I don't have a problem with downgrading it 😄

**Comment by mockersf** [comment]
@clux is it ok for you now ?

**Comment by clux** [comment]
Yes, thanks a lot!
