### ISSUE TITLE
Support optional tree query parameter.

### ISSUE THREAD

**Issue by davidtwco** [mockersf/jenkins-api.rs#19]
You can read about the tree parameter [in this blog post](https://www.cloudbees.com/blog/taming-jenkins-json-api-depth-and-tree).

**Comment by mockersf** [comment]
Hello !

My issue with the tree parameter is that I don't see how to use it and still translate the json to a defined type, as it will change the fields present in the response...

I'm open to discuss the subject if you have ideas about that ! 😄

**Comment by davidtwco** [comment]
Perhaps instead of having all of the fields on something like `CommonBuild` be public, you could have accessor functions, ie. instead of `build.queue_id` it would be `build.queue_id()` and then the internal state of `CommonBuild` would just contain a `serde_json::Value` that you could inspect when a accessor is called. This would work, but you'd end up with every function returning a `Option<_>` since we wouldn't know at compile-time which fields the user will request - that isn't as nice. 

Or instead, I wonder if you could build a macro/custom derive that takes the `tree` parameter and implements a trait on a user's type for those specified fields. The functions on the `Jenkins` struct could return differently depending on the type of the variable being assigned - similar to how in `serde_json` a function would work for `let x: Value = serde_json::...` or `let x: MyType = serde_json:...`?

I'm not sure how viable either of these ideas are, just some suggestions.

**Comment by mockersf** [comment]
I tried something for jobs : https://mockersf.github.io/jenkins-api.rs/jenkins_api/client/struct.Jenkins.html#method.get_job_as

If it looks good to you I'll generalise it for other objects

example usage:
```rust
    let job_as_json: Result<serde_json::Value, _> = jenkins.get_job_as(
        "job name",
        Some(jenkins_api::client::AdvancedQuery::Depth(0)),
    );

    let url_reason_and_cause: Result<serde_json::Value, _> = jenkins.get_job_as(
        "job name",
        Some(jenkins_api::client::AdvancedQuery::Tree(
            jenkins_api::client::TreeQueryParam {
                keyname: "builds".to_string(),
                fields: vec!["url".to_string(), "result".to_string()],
                subkeys: vec![jenkins_api::client::TreeQueryParam {
                    keyname: "actions".to_string(),
                    fields: vec!["causes".to_string()],
                    subkeys: vec![],
                }],
            },
        )),
    );
```

I'm not completely convinced with [`TreeQueryParam`](https://mockersf.github.io/jenkins-api.rs/jenkins_api/client/struct.TreeQueryParam.html), I would like a way to use a string directly but that would fail cleanly if the string is invalid...

**Comment by mockersf** [comment]
From my test, when you use `depth` with `tree`, `depth` is ignored.

I liked your builder idea:
```rust
let job: Result<serde_json::Value, _> = jenkins.get_job_as(
    "job name",
    TreeBuilder::new()
        .with_field("displayName")
        .with_field(
            TreeBuilder::object("lastBuild")
                .with_subfield("number")
                .with_subfield("duration")
                .with_subfield("result"),
        )
        .build(),
);
```

[builder doc](https://mockersf.github.io/jenkins-api.rs/jenkins_api/client/struct.TreeBuilder.html)

**Comment by davidtwco** [comment]
It seems you're right, Jenkins' API doesn't work with `tree` and `depth` simultaneously. I think the builder route is definitely the correct way to approach this API, the current implementation looks pretty good.

**Comment by davidtwco** [comment]
@mockersf I've been thinking and it might be nice to support a "advanced query" API - this would look something like this and exist in parallel with the current API:

```rust
// Instead of `CommonJob`, this could be `serde_json::Value` or a custom struct by the user
// that has only the expected fields.
let job = Result<CommonJob, _> = AdvancedQueryBuilder::with_depth(1)
    // perhaps have a `InProgressQueryWithDepth` and `InProgressQueryWithFields` that implement
    // the same trait as `AdvancedQueryBuilder` so they all have the `get_job` methods and equivalent
    // but limit the user's ability to use both depth and tree parameters at the same time which doesn't
    // work and is confusing.
    .field("displayName")
    .field("lastBuild".as_field()
           .subfield("number")
           .subfield("duration")
           .subfield("timestamp"))
    .get_job("job name") // a function like this for each 
    .execute(&jenkins);
```
(very slightly different from a previous example)

In particular, my reason for wanting this is that currently you can't configure the `depth` parameter on a per-API call basis - this API would allow that and also would support the `tree` parameter. In my experiences with this library, if I want to use `?depth=1` on a API call for a build then that's fine but it might also make the amount of memory being allocated skyrocket when the `?depth=1` parameter makes an API call for a job return a massive amount of data.

**Comment by mockersf** [comment]
Then you want the new [`get_object_as`](https://mockersf.github.io/jenkins-api.rs/jenkins_api/struct.Jenkins.html#method.get_object_as)
It's pretty much the same as `get_job_as` but instead of passing directly the job name, you pass a [`Path`](https://mockersf.github.io/jenkins-api.rs/jenkins_api/client/enum.Path.html) which can be translated into a Jenkins url.

For example: 
```rust
    let r: Result<LasBuildOfJob, _> = jenkins.get_object_as(
        jenkins_api::client::Path::Job {
            name: "job name",
            configuration: None,
        },
        jenkins_api::client::TreeBuilder::new()
            .with_field("displayName")
            .with_field(
                jenkins_api::client::TreeBuilder::object("lastBuild")
                    .with_subfield("number")
                    .with_subfield("duration")
                    .with_subfield("result"),
            )
            .build(),
    );
```

**Comment by davidtwco** [comment]
Thanks! I hadn't noticed that. I'll close this issue as this functionality is now supported (though not yet released).

**Comment by mockersf** [comment]
Actually I pushed this method just before commenting 😄 

It has now been released
