### ISSUE TITLE
new release with reqwest bump

### ISSUE THREAD

**Issue by clux** [mockersf/jenkins-api.rs#27]
Hey there :slightly_smiling_face: 

Any chance we could get a patch bump release of the latest changeset?

latest released crate does not build, but:

```toml
jenkins_api = { git = "https://github.com/mockersf/jenkins-api.rs", rev = "7b7325d0447dbfe82080f99fcbfddd9030cf7e93" }
```

^ does

**Comment by mockersf** [comment]
Sure !
https://crates.io/crates/jenkins_api/0.5.1 has been released.
request crate changed a lot of things in it's header management, that was probably the source of your issues

**Comment by clux** [comment]
Thanks. Yeah, think the entire ecosystem needs a bump because of https://github.com/sfackler/rust-openssl/issues/987
