### ISSUE TITLE
Color seems to be an optional field

### ISSUE THREAD

**Issue by ardouglas** [mockersf/jenkins-api.rs#37]
Hi,  thank you very much for this great library!  I have an issue when using the get_view method.  It seems that the response from my Jenkins server does not include the color field for every job.  I cloned your repo and modified src/job/common.rs in two places and that fixed the issue for me.

I changed the two lines that were
pub color: BallColor,

to 
pub color: Option<BallColor>,

If you are interested in these changes I can submit a PR.  Thanks again for the awesome library!

**Comment by mockersf** [comment]
sorry for the delay, I'm pushing the change now in v0.6.0
