### ISSUE TITLE
Unhide the `other_fields` from CommonAction struct.

### ISSUE THREAD

**Issue by rapidclock** [mockersf/jenkins-api.rs#52]
I am trying to parse the upstream job info from the Build information. This value is stored as part of the Vec<CommonAction> that is the `action` field inside the build struct.

Unfortunately, since that is marked private(not marked pub), I cannot access the data.

It would be nice to expose that as the json object itself(since I see that it is stored as a serde_json object anyway).

**Comment by mockersf** [comment]
with feature `extra-fields-visibility`, this fields will be public
